### ISSUE TITLE
0.1.16.2 deletes PAW entry "Configure Vessel Naming"

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/FuseBoxContinued#13]
At least one entry is missing as far as I recognized:
In VAB the "Configure Vessel Naming" is gone.

Removing FuseBox 0.1.16.2 and it's back.

See
https://forum.kerbalspaceprogram.com/index.php?/topic/176183-vab-paw-entry-for-configure-vessel-naming-is-gone/

**Comment by linuxgurugamer** [comment]
Happens in 1.4.3 as well

**Comment by linuxgurugamer** [comment]
And most likely all of the 1.4 series

**Comment by linuxgurugamer** [comment]
This problem popped up in 1.4.3, but no one reported it.
I've fixed it for now
