### ISSUE TITLE
Sun Exposure Slider & Distance from Sun

### ISSUE THREAD

**Issue by StahnAileron** [linuxgurugamer/FuseBoxContinued#5]
After having written my other suggestion (Orbital Period & Time to Full Charge), I realized solar panels are really variable due to sun-tracking and the inverse-square law.

So I'm thinking a slider for solar panels exposure (just like the engine power slider for alternators/ions). For distance from the sun, simplest is probably a text box like the Dark-time altitude (km - defaults to Kerbin's orbital distance) .

**Comment by linuxgurugamer** [comment]
Closing in favor of #6 which has more detail (looks like we both added it about the same time
